name: Java CI with Maven

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: event_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Checkout do repositório
      uses: actions/checkout@v3
    
    - name: Configurar JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Criar schema no banco de dados
      run: |
        sudo apt-get install -y postgresql-client
        PGPASSWORD=postgres psql -h localhost -U postgres -d event_db -c "CREATE SCHEMA IF NOT EXISTS event_system;"

    - name: Configurar variáveis de ambiente para testes
      run: |
        echo "SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:5432/event_db" >> $GITHUB_ENV
        echo "SPRING_DATASOURCE_USERNAME=postgres" >> $GITHUB_ENV
        echo "SPRING_DATASOURCE_PASSWORD=postgres" >> $GITHUB_ENV

    - name: Build com Maven
      working-directory: ./event-system
      run: mvn -B package --file pom.xml

    - name: Executar testes com cobertura
      working-directory: ./event-system
      run: mvn test jacoco:report

    - name: Upload do relatório de cobertura
      uses: actions/upload-artifact@v4
      with:
        name: jacoco-report
        path: |
          event-system/target/site/jacoco/
          event-system/target/jacoco.exec
          event-system/target/jacoco-report.xml
