name: Java CI with Maven

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do repositório
      uses: actions/checkout@v3
    
    - name: Configurar JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build com Maven
      working-directory: ./event-system
      run: mvn -B package --file pom.xml

    - name: Executar testes com cobertura
      working-directory: ./event-system
      run: mvn test jacoco:report

    - name: Upload do relatório de cobertura
      uses: actions/upload-artifact@v4
      with:
        name: jacoco-report
        path: |
          event-system/target/site/jacoco/
          event-system/target/jacoco.exec
          event-system/target/jacoco-report.xml
