name: Java CI with Maven (Testes Unitários e Integração)
on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout do repositório
      uses: actions/checkout@v3
    
    - name: Configurar JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    
    - name: Setup Docker
      uses: docker/setup-buildx-action@v2

    - name: Verificar Docker
      run: |
        docker --version
        docker ps
        docker info
    
    - name: Configurar TestContainers
      run: |
        echo "TESTCONTAINERS_RYUK_DISABLED=true" >> $GITHUB_ENV
        echo "TESTCONTAINERS_CHECKS_DISABLE=true" >> $GITHUB_ENV
        # Esta opção melhora a eficiência dos testes que usam TestContainers
        echo "TESTCONTAINERS_REUSE_ENABLE=true" >> $GITHUB_ENV
    
    - name: Compilar projeto
      working-directory: ./event-system
      run: mvn -B clean compile
      
    - name: Executar todos os testes
      working-directory: ./event-system
      run: mvn verify

    - name: Gerar relatório de cobertura
      working-directory: ./event-system
      run: mvn jacoco:report
    
    - name: Upload do relatório de cobertura
      uses: actions/upload-artifact@v4
      with:
        name: jacoco-report
        path: |
          event-system/target/site/jacoco/
          event-system/target/jacoco.exec
    
    - name: Empacotar
      if: success()
      working-directory: ./event-system
      run: mvn -B package -DskipTests
      
    - name: Upload do artefato JAR
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: event-system-jar
        path: event-system/target/event-system-*.jar
